language: go

go:
  - 1.9

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn

jobs:
  include:
    - stage: Tests, linters and build
      script:
        - make lint-frontend
        - make test-frontend
        - make lint-backend
        - make test
        - make validate-commit
    - script:
        - make build-app
